#Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer_behaviour
GROUP BY gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer_behaviour
WHERE discount_applied = 'Yes'
AND purchase_amount >
    (SELECT AVG(purchase_amount)
     FROM customer_behaviour);
     
#Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    AVG(review_rating) AS avg_rating
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

#Q4. Compare the average purchase amounts between Standard and Express shipping.
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer_behaviour
GROUP BY shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer_behaviour
GROUP BY subscription_status;

#Q6. Which products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
    / COUNT(*) AS discount_percentage
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY discount_percentage DESC;


#Q7. Segment customers into New, Returning, and Loyal based on previous purchases and show count.
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_behaviour
GROUP BY customer_segment
ORDER BY customer_count DESC;

#with CTE
WITH customer_segments AS (
    SELECT 
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_behaviour
)
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM customer_segments
GROUP BY customer_segment
ORDER BY customer_count DESC;


#Q8. What are the top 3 most purchased products within each category?
SELECT category, item_purchased, purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM customer_behaviour
    GROUP BY category, item_purchased
) t
WHERE rnk <= 3;

#Q9. Are repeat buyers (more than 5 previous purchases) also likely to be subscribers?
SELECT 
    subscription_status,
    COUNT(*) AS repeat_buyers
FROM customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC;






